package br.usp.ime.jdx.entity.relationship.dependency;

public enum DependencyType{

	CLASS_INHERITANCE,
	INTERFACE_INHERITANCE,
	INTERFACE_IMPLEMENTATION,
	METHOD_CALL,
	REFERENCE,
	ACCESS,
	METHOD_RETURN,
	METHOD_PARAM,
	THROWN_EXCEPTION,
	PACKAGE_IMPORT,
	TYPE_IMPORT,
	STATIC_IMPORT,
	COMP_UNIT_META_DEPENDENCY,
	TYPE_META_DEPENDENCY;
	
}
